### PR TITLE
Correctly loading item map and QR code scanner

### LINKED ISSUE #135: Turbolink not loading assets (in web?)
As a developer, I want to find a way to load different assets (like the camera for QR-code scanning), when switching pages via turbolinks.

### Acceptance Criteria

- [ ]  Every external asset is shown without needing to reload.

For questions regarding this issue, reach out to: @LeoKohlenberg

### LINKED ISSUE #183: Fix: Camera opens only on page refresh
When I use the QR code button to scan an item, the camera does not open. Only after I refresh the page the camera opens. I want it to open directly, not requireing the page refresh.

Screenshot 2022-12-20 222254

### PR DESCRIPTION
**Pull request by codingWhale13**
This fixes #135 and thereby fixes #183.

### CODE REVIEW

**Comment by Alorcus** [comment]
@codingWhale13 Does it also fix #135?

**Comment by codingWhale13** [comment]
> @codingWhale13 Does it also fix #135?

With the second commit in this PR, it does. :) The map had a similar issue which is now fixed similarly to the issue on the scanning page.

On my machine, everything works fine now and map as well as QR code scanner load immediately, without having to refresh manually. If you notice any odd behavior, let me know!

**Comment by Alorcus** [comment]
> > @codingWhale13 Does it also fix #135?
> 
> Thanks for pointing this out! With the second commit in this PR, it now does. :) I edited the PR message to also address issue #135. The map had a similar issue which is now fixed similarly to the issue on the scanning page.
> 
> On my machine, everything works fine now and the map as well as the QR code scanner load immediately, without having to refresh manually. If you notice any odd behavior, let me know!

Great! Thank you!

**Comment by LeoKohlenberg** [comment]
Great that you found a solution, LGTM 🚀

**Review by LeoKohlenberg — APPROVED** [review]
Great that you found a solution, LGTM 🚀

**Review by FSadrieh — APPROVED** [review]

**Pull request merged**
