### PR TITLE
feat: run rubocop as part of CI

### PR DESCRIPTION
**Pull request by Skn0tt**
Our Leitfaden mentions that Rubocop needs to pass before a PR can be merged. This PR enforces this by adding a check to CI.

### CODE REVIEW

**Comment by Skn0tt** [comment]
cc @yannik-dittmar @Shieka

**Comment by yannik-dittmar** [comment]
What is the status of this PR? What needs to be done to merge it? I would suggest fixing all Rubocop issues, so the CI is green again and of course resolving the merge conflicts.

**Comment by Skn0tt** [comment]
Sounds good, yeah! Let's do that together tomorrow.

**Review by yannik-dittmar — APPROVED** [review]
LGTM

**Pull request merged**
