### PR TITLE
fix: position footer correctly

### LINKED ISSUE #227: Footer does not align with the bottom
The footer does not align with the bottom of the website.
Bug appeared in the main.

grafik

### Acceptance Criteria

- [ ]  The footer should align with the bottom of the website.

### PR DESCRIPTION
**Pull request by gwauge**
- use page wrapper around content and footer
- credits to https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/
- Resolves #227

### CODE REVIEW

**Review by Glitterrosie — CHANGES_REQUESTED** [review]
image

The problem does not seem to be fully resolved yet.

**Comment by Glitterrosie** [comment]
image

**Comment by gwauge** [comment]
Precompilation of assets required for changes to take effect:
```
rails assets:precompile
```

**Review by Glitterrosie — APPROVED** [review]
Very easy and straight forward approach!

**Pull request merged**
